### ISSUE TITLE
Cant add Images In markdown 

### ISSUE THREAD

**Issue by gramythedj** [httpsterio/httpster.io#20]
when i add images for example 
"<  img src="img_g  irl.jpg" alt="Girl i"   width="500" height="600"   >"

then only alt tag is shown and not the image, it shown as null

The only working way to add an image is by URL

**Comment by httpsterio** [comment]
Hey, thanks for the issue. I'll try to verify the same issue on my end. 

My gut instinct is that this is related to an issue I raised in the original repo I forked it from. Check [this issue](https://github.com/MadeByMike/supermaya/issues/32) out and see if could be the same?

**Comment by httpsterio** [comment]
I cannot replicate the issue myself.

Are you sure you're linking to the images correctly? In my case, I'm throwing the images in the ```/static/img``` folder and in ```.eleventy.js``` config file on line 67 that gets passed through to ```/img``` when building it. This means that images for me are reachable in articles by refering them to as ```/img/image-name.png``` and in the final site they'll be available at ```https://httpster.io/img/image-name.png```.

If you're not saving images to the ```/static/img``` folder, you might have to add a addPassThroughCopy and make note of where you're sending the images to.

https://httpster.io/article/2021-07-02-test-post/
Here's a demo post I made with some images. The markdown code for them are attached at the bottom so you can see how I formatted it.

If you give an image a title, it'll get wrapped in a ```<figure>``` and the title will be added as a caption to the image.

If you're using the markdown syntax ```![alt text](url)```, the text you put in the brackets will become the alt text for that image. If you want to use lazy loading, you'll have to manually provide a ```data-src``` url on top of the regular ```src```.

**Comment by httpsterio** [comment]
closing the issue as i cant replicate it
